spring:
  application:
    name: spring-ai-functions
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 11MB
  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
